<?php
// 1100-ERP System Configuration File
// Generated by Setup Wizard on: 2026-01-26 22:41:19

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'bluedotserp');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PREFIX', 'erp_');

// Establish Database Connection
try {
    $dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4";
    $pdo = new PDO($dsn, DB_USER, DB_PASS, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
        PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
    ]);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

// Helper function to get settings
function getSetting($key, $default = '')
{
    global $pdo;
    try {
        $stmt = $pdo->prepare("SELECT setting_value FROM settings WHERE setting_key = ?");
        $stmt->execute([$key]);
        $result = $stmt->fetch();
        return $result ? $result['setting_value'] : $default;
    } catch (PDOException $e) {
        return $default;
    }
}

// Load basic settings into constants
define('COMPANY_NAME', getSetting('company_name', 'Your Company Name'));
define('TINYMCE_API_KEY', getSetting('tinymce_api_key', 'no-api-key'));
define('COMPANY_LOGO', getSetting('company_logo', ''));
define('COMPANY_ADDRESS', getSetting('company_address', ''));
define('COMPANY_PHONE', getSetting('company_phone', ''));
define('COMPANY_EMAIL', getSetting('company_email', ''));
define('COMPANY_WEBSITE', getSetting('company_website', ''));
define('VAT_RATE', (float) getSetting('vat_rate', 7.5));
define('CURRENCY_SYMBOL', getSetting('currency_symbol', '₦'));

// Additional Display Settings
define('THEME_COLOR', getSetting('theme_color', '#0076BE'));
define('FOOTER_TEXT', getSetting('footer_text', 'We appreciate your business! Thank you'));
define('PDF_QUALITY', getSetting('pdf_quality', 'high'));
define('DEFAULT_PAYMENT_TERMS', getSetting('payment_terms', 'Due on Receipt'));

// Bank account helper functions
function getBankAccountsForDisplay()
{
    global $pdo;
    try {
        $stmt = $pdo->query("
            SELECT * FROM bank_accounts 
            WHERE is_active = 1 AND show_on_documents = 1 
            ORDER BY display_order ASC
        ");
        return $stmt->fetchAll();
    } catch (PDOException $e) {
        return [];
    }
}

function getAllBankAccounts()
{
    global $pdo;
    try {
        $stmt = $pdo->query("
            SELECT * FROM bank_accounts 
            WHERE is_active = 1 
            ORDER BY display_order ASC
        ");
        return $stmt->fetchAll();
    } catch (PDOException $e) {
        return [];
    }
}

function getSelectedBankAccountsCount()
{
    global $pdo;
    try {
        $stmt = $pdo->query("
            SELECT COUNT(*) as count 
            FROM bank_accounts 
            WHERE is_active = 1 AND show_on_documents = 1
        ");
        $result = $stmt->fetch();
        return $result['count'];
    } catch (PDOException $e) {
        return 0;
    }
}